# Thai translation for apport
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the apport package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: apport\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-08-19 15:19+0200\n"
"PO-Revision-Date: 2011-10-07 06:10+0000\n"
"Last-Translator: Martin Pitt <martin.pitt@ubuntu.com>\n"
"Language-Team: Thai <th@li.org>\n"
"Language: th\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2022-08-19 12:20+0000\n"
"X-Generator: Launchpad (build 87919ae1fbf1142b0e02b80650e6ccf3e775beb3)\n"

#: ../apport/com.ubuntu.apport.policy.in.h:1
msgid "Collect system information"
msgstr "รวบรวมข้อมูลของระบบ"

#: ../apport/com.ubuntu.apport.policy.in.h:2
msgid ""
"Authentication is required to collect system information for this problem "
"report"
msgstr "ต้องยืนยันตัวตนเพื่อรวบรวมข้อมูลของระบบเพื่อใช้รายงานปัญหาในครั้งนี้"

#: ../apport/com.ubuntu.apport.policy.in.h:3
msgid "System problem reports"
msgstr "การรายงานปัญหาระบบ"

#: ../apport/com.ubuntu.apport.policy.in.h:4
msgid "Please enter your password to access problem reports of system programs"
msgstr "โปรดป้อนรหัสผ่านเพื่อเข้าถึงรายงานปัญหาของโปรแกรมระบบ"

#: ../apport/ui.py:164
msgid "This package does not seem to be installed correctly"
msgstr "ดูเหมือนว่าแพคเกจนี้จะไม่ได้ถูกติดตั้งอย่างถูกต้อง"

#: ../apport/ui.py:174
#, python-format
msgid ""
"This does not seem to be an official %s package. Please retry after updating "
"the indexes of available packages, if that does not work then remove related "
"third party packages and try again."
msgstr ""

#: ../apport/ui.py:204
#, python-format
msgid ""
"You have some obsolete package versions installed. Please upgrade the "
"following packages and check if the problem still occurs:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:358
msgid "unknown program"
msgstr ""

#: ../apport/ui.py:361
#, python-format
msgid "Sorry, the program \"%s\" closed unexpectedly"
msgstr ""

#: ../apport/ui.py:364 ../apport/ui.py:1898
#, python-format
msgid "Problem in %s"
msgstr ""

#: ../apport/ui.py:369
msgid ""
"Your computer does not have enough free memory to automatically analyze the "
"problem and send a report to the developers."
msgstr ""

#: ../apport/ui.py:429 ../apport/ui.py:447 ../apport/ui.py:620
#: ../apport/ui.py:629 ../apport/ui.py:866 ../apport/ui.py:1676
#: ../apport/ui.py:1859 ../apport/ui.py:1864
msgid "Invalid problem report"
msgstr ""

#: ../apport/ui.py:430
msgid "You are not allowed to access this problem report."
msgstr ""

#: ../apport/ui.py:438
msgid "Error"
msgstr ""

#: ../apport/ui.py:440
msgid "There is not enough disk space available to process this report."
msgstr ""

#: ../apport/ui.py:478
msgid "No PID specified"
msgstr ""

#: ../apport/ui.py:480
msgid "You need to specify a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:491 ../apport/ui.py:596
msgid "Invalid PID"
msgstr ""

#: ../apport/ui.py:492
msgid "The specified process ID does not exist."
msgstr ""

#: ../apport/ui.py:497
msgid "Not your PID"
msgstr ""

#: ../apport/ui.py:498
msgid "The specified process ID does not belong to you."
msgstr ""

#: ../apport/ui.py:553
msgid "No package specified"
msgstr ""

#: ../apport/ui.py:555
msgid ""
"You need to specify a package or a PID. See --help for more information."
msgstr ""

#: ../apport/ui.py:583
msgid "Permission denied"
msgstr ""

#: ../apport/ui.py:585
msgid ""
"The specified process does not belong to you. Please run this program as the "
"process owner or as root."
msgstr ""
"กระบวนการที่ระบุไม่ใช่ของคุณ "
"โปรดเรียกใช้โปรแกรมนี้ในฐานะเจ้าของกระบวนการหรือในฐานะผู้ดูแลระบบขั้นสูง"

#: ../apport/ui.py:598
msgid "The specified process ID does not belong to a program."
msgstr "ID ของกระบวนการที่ระบุไม่ใช่ของโปรแกรมใด"

#: ../apport/ui.py:622
#, python-format
msgid "Symptom script %s did not determine an affected package"
msgstr "สคริปต์อาการ %s ไม่ได้กำหนดแพกเกจที่ได้รับผลกระทบ"

#: ../apport/ui.py:630
#, python-format
msgid "Package %s does not exist"
msgstr ""

#: ../apport/ui.py:659 ../apport/ui.py:871 ../apport/ui.py:904
#: ../apport/ui.py:914
msgid "Cannot create report"
msgstr ""

#: ../apport/ui.py:674 ../apport/ui.py:733 ../apport/ui.py:751
msgid "Updating problem report"
msgstr ""

#: ../apport/ui.py:676
msgid ""
"You are not the reporter or subscriber of this problem report, or the report "
"is a duplicate or already closed.\n"
"\n"
"Please create a new report using \"apport-bug\"."
msgstr ""
"คุณไม่ใช่ผู้รายงานหรือผู้ติดตามรายงานปัญหานี้ หรือรายงานนี้อาจมีการเชื่อมโยงซ้ำ หรือถูกปิดไปแล้ว\n"
"\n"
"โปรดสร้างรายงานใหม่โดยใช้ \"apport-bug\""

#: ../apport/ui.py:688
msgid ""
"You are not the reporter of this problem report. It is much easier to mark a "
"bug as a duplicate of another than to move your comments and attachments to "
"a new bug.\n"
"\n"
"Subsequently, we recommend that you file a new bug report using \"apport-"
"bug\" and make a comment in this bug about the one you file.\n"
"\n"
"Do you really want to proceed?"
msgstr ""
"คุณไม่ใช้ผู้รายงานปัญหานี้ "
"การที่คุณทำเครื่องหมายปัญหานี้ว่ามีการเชื่อมโยงซ้ำง่ายกว่าการที่คุณย้ายความคิดเห็นและสิ่งที่แนบมาไปยังปัญหาใหม่\n"
"\n"
"เราขอแนะนำให้คุณรายงานปัญหาใหม่โดยใช้ \"apport-bug\" "
"แล้วสร้างความคิดเห็นเกี่ยวกับปัญหาที่คุณรายงานนี้\n"
"\n"
"คุณต้องการดำเนินการต่อไปหรือไม่?"

#: ../apport/ui.py:734 ../apport/ui.py:752
msgid "No additional information collected."
msgstr "ไม่มีการรวบรวมข้อมูลเพิ่มเติมใด ๆ"

#: ../apport/ui.py:815
msgid "What kind of problem do you want to report?"
msgstr ""

#: ../apport/ui.py:836
msgid "Unknown symptom"
msgstr ""

#: ../apport/ui.py:837
#, python-format
msgid "The symptom \"%s\" is not known."
msgstr ""

#: ../apport/ui.py:873
msgid ""
"The window option cannot be used on Wayland.\n"
"\n"
"Please find the window's process ID and then run 'ubuntu-bug <process ID>'.\n"
"\n"
"The process ID can be found by running the System Monitor application. In "
"the Processes tab, scroll until you find the correct application. The "
"process ID is the number listed in the ID column."
msgstr ""

#: ../apport/ui.py:889
msgid ""
"After closing this message please click on an application window to report a "
"problem about it."
msgstr "หลังจากที่ปิดข้อความนี้แล้ว โปรดคลิกบนหน้าต่างโปรแกรมเพื่อรายงานปัญหานี้"

#: ../apport/ui.py:906 ../apport/ui.py:915
msgid "xprop failed to determine process ID of the window"
msgstr "xprop ไม่สามารถกำหนด ID โปรเซสของหน้าต่างได้"

#: ../apport/ui.py:930
#, python-format
msgid "%(prog)s <report number>"
msgstr ""

#: ../apport/ui.py:931
msgid "Specify package name."
msgstr "ระบุชื่อแพกเกจ"

#: ../apport/ui.py:937 ../apport/ui.py:1069
msgid "Add an extra tag to the report. Can be specified multiple times."
msgstr "เพิ่มแท็กพิเศษไปในรายงาน สามารถระบุได้หลาย ๆ ครั้ง"

#: ../apport/ui.py:975
#, python-format
msgid ""
"%(prog)s [options] [symptom|pid|package|program path|.apport/.crash file]"
msgstr ""

#: ../apport/ui.py:986
msgid ""
"Start in bug filing mode. Requires --package and an optional --pid, or just "
"a --pid. If neither is given, display a list of known symptoms. (Implied if "
"a single argument is given.)"
msgstr ""
"เริ่มทำงานในโหมดรายงานปัญหา ต้องใช้ --package และ --pid พร้อมตัวเลือก หรือเพียง --pid "
"ถ้าไม่ใส่อาร์กิวเมนต์ดังกล่าว ให้แสดงรายการอาการที่รู้ว่าเกิดขึ้น "
"(ไม่ทำงานถ้าใส่เพียงอาร์กิวเมนต์เดียว)"

#: ../apport/ui.py:995
msgid "Click a window as a target for filing a problem report."
msgstr "คลิกหน้าต่างเพื่อเป็นเป้าหมายสำหรับรายงานปัญหา"

#: ../apport/ui.py:1004
msgid "Start in bug updating mode. Can take an optional --package."
msgstr "เริ่มทำงานในโหมดอัปเดตปัญหา สามารถใช้อาร์กิวเมนต์ --package พร้อมตัวเลือกได้"

#: ../apport/ui.py:1013
msgid ""
"File a bug report about a symptom. (Implied if symptom name is given as only "
"argument.)"
msgstr "รายงานปัญหาเกี่ยวกับอาการ (ไม่ทำงานถ้าชื่ออาการถูกใส่เพียงอาร์กิวเมนต์)"

#: ../apport/ui.py:1022
msgid ""
"Specify package name in --file-bug mode. This is optional if a --pid is "
"specified. (Implied if package name is given as only argument.)"
msgstr ""
"ระบุชื่อแพกเกจในโหมด --file-bug ถ้าระบุ --pid นี่จะเป็นตัวเลือก "
"(ไม่ทำงานถ้าชื่อแพกเกจถูกใส่เพียงอาร์กิวเมนต์)"

#: ../apport/ui.py:1033
msgid ""
"Specify a running program in --file-bug mode. If this is specified, the bug "
"report will contain more information.  (Implied if pid is given as only "
"argument.)"
msgstr ""
"ระบุโปรแกรมที่กำลังทำงานในโหมด --file-bug ถ้ามีการระบุ "
"รายงานปัญหาจะประกอบด้วยข้อมูลเพิ่มเติม  (ไม่ทำงานถ้า pid ถูกใส่เพียงอาร์กิวเมนต์)"

#: ../apport/ui.py:1041
msgid "The provided pid is a hanging application."
msgstr "pid ที่ระบุเป็นโปรแกรมที่ทำงานค้างอยู่"

#: ../apport/ui.py:1049
#, python-format
msgid ""
"Report the crash from given .apport or .crash file instead of the pending "
"ones in %s. (Implied if file is given as only argument.)"
msgstr ""
"รายงานความล้มเหลวจากแฟ้ม .apport หรือ .crash ที่ให้มาแทนที่กำลังรออยู่ใน %s "
"(ไม่ทำงานถ้าแฟ้มถูกใส่เพียงอาร์กิวเมนต์)"

#: ../apport/ui.py:1059
msgid ""
"In bug filing mode, save the collected information into a file instead of "
"reporting it. This file can then be reported later on from a different "
"machine."
msgstr ""
"ในโหมดรายงานปัญหา บันทึกข้อมูลที่รวบรวมเป็นแฟ้มแทนที่จะรายงาน "
"แฟ้มนี้สามารถเก็บไว้รายงานได้ทีหลังโดยใช้เครื่องอื่นได้"

#: ../apport/ui.py:1077
msgid "Print the Apport version number."
msgstr ""

#: ../apport/ui.py:1239
msgid ""
"This will launch apport-retrace in a terminal window to examine the crash."
msgstr ""
"การดำเนินการนี้จะเป็นการเรียกใช้ apport-retrace ในหน้าต่างเทอร์มินัลเพื่อตรวจสอบความล้มเหลว"

#: ../apport/ui.py:1243
msgid "Run gdb session"
msgstr "เรียกใช้วาระ gdb"

#: ../apport/ui.py:1244
msgid "Run gdb session without downloading debug symbols"
msgstr "เรียกใช้วาระ gdb session โดยไม่ต้องดาวน์โหลดสัญลักษณ์การดีบั๊ก"

#. TRANSLATORS: %s contains the crash report file name
#: ../apport/ui.py:1246
#, python-format
msgid "Update %s with fully symbolic stack trace"
msgstr "อัปเดต %s พร้อมข้อมูลการติดตามสแตกเชิงสัญลักษณ์"

#: ../apport/ui.py:1308
msgid "Can't remember send report status settings"
msgstr ""

#: ../apport/ui.py:1312
msgid ""
"Saving crash reporting state failed. Can't set auto or never reporting mode."
msgstr ""

#: ../apport/ui.py:1395 ../apport/ui.py:1408
msgid ""
"This problem report applies to a program which is not installed any more."
msgstr "รายงานปัญหานี้จะนำไปใช้กับโปรแกรมที่ไม่ได้ติดตั้งอีกต่อไป"

#: ../apport/ui.py:1432
#, python-format
msgid ""
"The problem happened with the program %s which changed since the crash "
"occurred."
msgstr "มีปัญหาเกิดขึ้นกับโปรแกรม %s ซึ่งมีการเปลี่ยนแปลงตั้งแต่เกิดความล้มเหลวขึ้น"

#: ../apport/ui.py:1493 ../apport/ui.py:1617 ../apport/ui.py:1868
msgid "This problem report is damaged and cannot be processed."
msgstr ""

#: ../apport/ui.py:1502
msgid "This report is about a package that is not installed."
msgstr ""

#: ../apport/ui.py:1510
msgid "An error occurred while attempting to process this problem report:"
msgstr "เกิดข้อผิดพลาดขณะพยายามประมวลผลการรายงานปัญหานี้:"

#: ../apport/ui.py:1527
msgid ""
"You have two versions of this application installed, which one do you want "
"to report a bug against?"
msgstr ""

#: ../apport/ui.py:1532
#, python-format
msgid "%s snap"
msgstr ""

#: ../apport/ui.py:1533
#, python-format
msgid "%s deb package"
msgstr ""

#: ../apport/ui.py:1574
#, python-format
msgid "%s is provided by a snap published by %s. Contact them via %s for help."
msgstr ""

#: ../apport/ui.py:1579
#, python-format
msgid ""
"%s is provided by a snap published by %s. No contact address has been "
"provided; visit the forum at https://forum.snapcraft.io/ for help."
msgstr ""

#: ../apport/ui.py:1678
msgid "Could not determine the package or source package name."
msgstr "ไม่สามารถกำหนดแพกเกจหรือชื่อแพกเกจต้นฉบับได้"

#: ../apport/ui.py:1703
msgid "Unable to start web browser"
msgstr ""

#: ../apport/ui.py:1704
#, python-format
msgid "Unable to start web browser to open %s."
msgstr ""

#: ../apport/ui.py:1814
msgid "Network problem"
msgstr ""

#: ../apport/ui.py:1818
msgid ""
"Cannot connect to crash database, please check your Internet connection."
msgstr ""
"ไม่สามารถเชื่อมต่อไปที่ฐานข้อมูลความล้มเหลวได้ โปรดตรวจสอบการเชื่อมต่ออินเทอร์เน็ตของคุณ"

#: ../apport/ui.py:1850
msgid "Memory exhaustion"
msgstr ""

#: ../apport/ui.py:1852
msgid "Your system does not have enough memory to process this crash report."
msgstr "ระบบของคุณมีหน่วยความจำไม่เพียงพอสำหรับประมวลผลการรายงานปัญหานี้"

#: ../apport/ui.py:1903
#, python-format
msgid ""
"The problem cannot be reported:\n"
"\n"
"%s"
msgstr ""

#: ../apport/ui.py:1959 ../apport/ui.py:1971
msgid "Problem already known"
msgstr ""

#: ../apport/ui.py:1961
msgid ""
"This problem was already reported in the bug report displayed in the web "
"browser. Please check if you can add any further information that might be "
"helpful for the developers."
msgstr ""
"ปัญหานี้ถูกรายงานอยู่แล้วในรายงานปัญหาที่แสดงในเว็บเบราว์เซอร์ "
"โปรดตรวจสอบว่าคุณสามารถเพิ่มข้อมูลเพิ่มเติมที่อาจเป็นประโยชน์ต่อนักพัฒนาได้หรือไม่"

#: ../apport/ui.py:1973
msgid "This problem was already reported to developers. Thank you!"
msgstr "ปัญหานี้ถูกรายงานให้ทางผู้พัฒนาไปแล้ว ขอขอบคุณ!"

#: ../bin/apport-cli.py:84
msgid "Press any key to continue..."
msgstr ""

#: ../bin/apport-cli.py:91
msgid "What would you like to do? Your options are:"
msgstr ""

#: ../bin/apport-cli.py:104
#, python-format
msgid "Please choose (%s):"
msgstr "โปรดเลือก (%s):"

#: ../bin/apport-cli.py:172
#, python-format
msgid "(%i bytes)"
msgstr "(%i ไบต์)"

#: ../bin/apport-cli.py:174 ../gtk/apport-gtk.py:168 ../kde/apport-kde.py:401
msgid "(binary data)"
msgstr "(binary data)"

#: ../bin/apport-cli.py:208 ../gtk/apport-gtk.py:207 ../gtk/apport-gtk.ui.h:6
#: ../kde/apport-kde.py:195
msgid "Send problem report to the developers?"
msgstr "ส่งรายงานปัญหาไปยังผู้พัฒนา?"

#: ../bin/apport-cli.py:210
msgid ""
"After the problem report has been sent, please fill out the form in the\n"
"automatically opened web browser."
msgstr ""
"หลังจากที่รายงานปัญหาถูกส่งไปแล้ว โปรดกรอกข้อมูลลงในแบบฟอร์ม\n"
"ในโปรแกรมท่องเว็บที่เปิดขึ้นมาโดยอัตโนมัติ"

#: ../bin/apport-cli.py:217
#, python-format
msgid "&Send report (%s)"
msgstr ""

#: ../bin/apport-cli.py:222
msgid "&Examine locally"
msgstr "&ตรวจในเครื่อง"

#: ../bin/apport-cli.py:226
msgid "&View report"
msgstr ""

#: ../bin/apport-cli.py:229
msgid "&Keep report file for sending later or copying to somewhere else"
msgstr "&เก็บแฟ้มรายงานไว้ส่งทีหลังหรือคัดลอกไปไว้ในที่อื่น ๆ"

#: ../bin/apport-cli.py:234
msgid "Cancel and &ignore future crashes of this program version"
msgstr "ยกเลิกและเพิกเ&ฉยต่อการขัดข้องครั้งหน้าของโปรแกรมรุ่นนี้"

#: ../bin/apport-cli.py:237 ../bin/apport-cli.py:331 ../bin/apport-cli.py:365
#: ../bin/apport-cli.py:388
msgid "&Cancel"
msgstr "&ยกเลิก"

#: ../bin/apport-cli.py:272
msgid "Problem report file:"
msgstr ""

#: ../bin/apport-cli.py:278 ../bin/apport-cli.py:283
msgid "&Confirm"
msgstr ""

#: ../bin/apport-cli.py:282
#, python-format
msgid "Error: %s"
msgstr ""

#: ../bin/apport-cli.py:288 ../kde/apport-kde.py:456
msgid "Collecting problem information"
msgstr "กำลังรวบรวมข้อมูลของปัญหา"

#: ../bin/apport-cli.py:290
msgid ""
"The collected information can be sent to the developers to improve the\n"
"application. This might take a few minutes."
msgstr ""
"ข้อมูลที่รวบรวมมาสามารถส่งไปให้นักพัฒนาเพื่อให้ทำการปรับปรุงโปรแกรมได้\n"
"การดำเนินการนี้จะใช้เวลาเพียงไม่กี่นาที"

#: ../bin/apport-cli.py:306 ../gtk/apport-gtk.ui.h:17 ../kde/apport-kde.py:504
msgid "Uploading problem information"
msgstr "กำลังอัปโหลดข้อมูลปัญหา"

#: ../bin/apport-cli.py:308
msgid ""
"The collected information is being sent to the bug tracking system.\n"
"This might take a few minutes."
msgstr ""
"ข้อมูลที่รวบรวมมากำลังจะถูกส่งไปยังระบบติด\n"
"ตามบั๊ก การดำเนินการนี้จะใช้เวลาเพียงไม่กี่นาที"

#: ../bin/apport-cli.py:364
msgid "&Done"
msgstr ""

#: ../bin/apport-cli.py:370
msgid "none"
msgstr ""

#: ../bin/apport-cli.py:372
#, python-format
msgid "Selected: %s. Multiple choices:"
msgstr "เลือกแล้ว: %s. หลายตัวเลือก:"

#: ../bin/apport-cli.py:389
msgid "Choices:"
msgstr ""

#: ../bin/apport-cli.py:403
msgid "Path to file (Enter to cancel):"
msgstr "เส้นทางมายังแฟ้ม (กด Enter เพื่อยกเลิก):"

#: ../bin/apport-cli.py:409
msgid "File does not exist."
msgstr ""

#: ../bin/apport-cli.py:411
msgid "This is a directory."
msgstr ""

#: ../bin/apport-cli.py:417
msgid "To continue, you must visit the following URL:"
msgstr ""

#: ../bin/apport-cli.py:420
msgid ""
"You can launch a browser now, or copy this URL into a browser on another "
"computer."
msgstr ""
"คุณสามารถเปิดโปรแกรมท่องเว็บได้แล้วตอนนี้ หรือคัดลอก URL "
"นี้ไปยังโปรแกรมท่องเว็บบนคอมพิวเตอร์เครื่องอื่น"

#: ../bin/apport-cli.py:426
msgid "Launch a browser now"
msgstr ""

#: ../bin/apport-cli.py:443
msgid "No pending crash reports. Try --help for more information."
msgstr "ไม่มีรายงานปัญหาที่รออยู่ ลองเรียกคำสั่ง --help เพื่อดูข้อมูลเพิ่มเติม"

#: ../bin/apport-retrace.py:44
msgid "Do not put the new traces into the report, but write them to stdout."
msgstr "ไม่ต้องเพิ่มการติดตามใหม่ลงในรายงาน แต่ให้เขียนไปที่ stdout"

#: ../bin/apport-retrace.py:53
msgid ""
"Start an interactive gdb session with the report's core dump (-o ignored; "
"does not rewrite report)"
msgstr ""
"เริ่มวาระ gdb แบบโต้ตอบพร้อมบันทึกหลักของรายงาน (ละเว้น -o; ไม่ต้องเขียนรายงานใหม่)"

#: ../bin/apport-retrace.py:62
msgid ""
"Write modified report to given file instead of changing the original report"
msgstr "เขียนรายงานที่ปรับเปลี่ยนไปที่แฟ้มที่ระบุแทนที่จะเปลี่ยนรายงานดั้งเดิม"

#: ../bin/apport-retrace.py:72
msgid "Remove the core dump from the report after stack trace regeneration"
msgstr "เอาบันทึกหลักออกจากรายงานหลังจากที่สร้างการติดตามสแตกใหม่แล้ว"

#: ../bin/apport-retrace.py:80
msgid "Override report's CoreFile"
msgstr "แทนที่ CoreFile ของรายงาน"

#: ../bin/apport-retrace.py:86
msgid "Override report's ExecutablePath"
msgstr "แทนที่ ExecutablePath ของรายงาน"

#: ../bin/apport-retrace.py:92
msgid "Override report's ProcMaps"
msgstr "แทนที่ ProcMaps ของรายงาน"

#: ../bin/apport-retrace.py:98
msgid "Rebuild report's Package information"
msgstr ""

#: ../bin/apport-retrace.py:105
msgid ""
"Build a temporary sandbox and download/install the necessary packages and "
"debug symbols in there; without this option it assumes that the necessary "
"packages and debug symbols are already installed in the system. The argument "
"points to the packaging system configuration base directory; if you specify "
"\"system\", it will use the system configuration files, but will then only "
"be able to retrace crashes that happened on the currently running release."
msgstr ""
"สร้าง Sandbox แบบชั่วคราวและดาวน์โหลด/ติดตั้งแพกเกจที่จำเป็นและสัญลักษณ์การดีบั๊กในนั้น "
"ถ้าไม่ใช้ตัวเลือกนี้ จะถือว่าแพกเกจที่จำเป็นและสัญลักษณ์การดีบั๊กได้ถูกติดตั้งไว้ในระบบแล้ว "
"อาร์กิวเมนต์จะบ่งชี้ไปที่ไดเรกทอรีพื้นฐานการกำหนดค่าระบบแพกเกจ ถ้าคุณระบุ \"system\" "
"ก็จะใช้เพียงแฟ้มกำหนดค่าของระบบ "
"แต่จะสามารถทำได้เพียงติดตามความล้มเหลวที่เกิดขึ้นเมื่อใช้รุ่นที่กำลังใช้งานอยู่ในขณะนี้เท่านั้น"

#: ../bin/apport-retrace.py:119
msgid ""
"Build another temporary sandbox for installing gdb and its dependencies "
"using the same release as the report rather than whatever version of gdb you "
"have installed."
msgstr ""
"สร้าง Sandbox ใหม่ชั่วคราวสำหรับติดตั้ง gdb และแพกเกจอื่นๆ "
"ที่เกี่ยวข้องโดยใช้รุ่นเดียวกับรายงานแทน gdb รุ่นที่คุณได้ติดตั้งไว้"

#: ../bin/apport-retrace.py:129
msgid "Report download/install progress when installing packages into sandbox"
msgstr "รายงานความคืบหน้าในการดาวน์โหลด/ติดตั้งระหว่างติดตั้งแพกเกจไปที่ Sandbox"

#: ../bin/apport-retrace.py:136
msgid "Prepend timestamps to log messages, for batch operation"
msgstr "ขึ้นต้นการประทับเวลาในข้อความปูม สำหรับดำเนินการชุดงาน"

#: ../bin/apport-retrace.py:142
msgid ""
"Create and use third-party repositories from origins specified in reports"
msgstr "สร้างและใช้ที่เก็บจากบุคคลที่สามจากแหล่งข้อมูลที่ระบุไว้ในรายงาน"

#: ../bin/apport-retrace.py:150
msgid "Cache directory for packages downloaded in the sandbox"
msgstr "ไดเรกทอรีแคชสำหรับแพกเกจที่ดาวน์โหลดใน Sandbox"

#: ../bin/apport-retrace.py:156
msgid ""
"Directory for unpacked packages. Future runs will assume that any already "
"downloaded package is also extracted to this sandbox."
msgstr ""
"ไดเรกทอรีสำหรับแพกเกจที่ยังไม่ได้แยก "
"การเรียกใช้งานครั้งต่อไปก็จะถือว่าแพกเกจที่ดาวน์โหลดไว้ถูกแยกไปที่ Sandbox แล้ว"

#: ../bin/apport-retrace.py:167 ../bin/apport-valgrind.py:97
msgid ""
"Install an extra package into the sandbox (can be specified multiple times)"
msgstr "ติดตั้งแพกเกจพิเศษไปที่ Sandbox (สามารถระบุได้หลายครั้ง)"

#: ../bin/apport-retrace.py:174
msgid ""
"Path to a file with the crash database authentication information. This is "
"used when specifying a crash ID to upload the retraced stack traces (only if "
"neither -g, -o, nor -s are specified)"
msgstr ""
"เส้นทางที่ไปยังแฟ้มที่มีข้อมูลการตรวจสอบความถูกต้องของฐานข้อมูลความล้มเหลว โดยจะถูกใช้เมื่อระบุ "
"ID ความล้มเหลวเพื่ออัปโหลดการติดตามสแตกที่มีการติดตามใหม่ (เฉพาะเมื่อไม่ได้ระบุ -g, -o, หรือ "
"-s)"

#: ../bin/apport-retrace.py:184
msgid ""
"Display retraced stack traces and ask for confirmation before sending them "
"to the crash database."
msgstr "แสดงการติดตามสแตกที่ติดตามใหม่และร้องขอการยืนยันก่อนที่จะส่งไปที่ฐานข้อมูลความล้มเหลว"

#: ../bin/apport-retrace.py:192
msgid "Path to the duplicate sqlite database (default: no duplicate checking)"
msgstr "เส้นทางที่ไปยังฐานข้อมูล sqlite ที่ทำซ้ำ (ค่าปริยาย: ไม่มีการตรวจสอบการทำซ้ำ)"

#: ../bin/apport-retrace.py:200
msgid "Do not add StacktraceSource to the report."
msgstr ""

#: ../bin/apport-retrace.py:213
msgid "You cannot use -C without -S. Stopping."
msgstr "คุณไม่สามารถใช้ -C โดยไม่ใช้ -S ได้ กำลังหยุดทำงาน"

#. translators: don't translate y/n,
#. apport currently only checks for "y"
#: ../bin/apport-retrace.py:243
msgid "OK to send these as attachments? [y/n]"
msgstr "ต้องการส่งเป็นสิ่งที่แนบมาหรือไม่? [y/n]"

#: ../bin/apport-unpack.py:29
#, python-format
msgid "%(prog)s <report> <target directory>"
msgstr ""

#: ../bin/apport-unpack.py:31
msgid "Report file to unpack"
msgstr ""

#: ../bin/apport-unpack.py:33
msgid "directory to unpack report to"
msgstr ""

#: ../bin/apport-unpack.py:45
msgid "Destination directory exists and is not empty."
msgstr "ไดเรกทอรีปลายทางมีอยู่และไม่ว่างเปล่า"

#: ../bin/apport-valgrind.py:37
msgid "See man page for details."
msgstr "ดูที่ Man page สำหรับรายละเอียดเพิ่มเติม"

#: ../bin/apport-valgrind.py:46
msgid "specify the log file name produced by valgrind"
msgstr "ระบุชื่อแฟ้มปูมที่สร้างขึ้นโดย valgrind"

#: ../bin/apport-valgrind.py:52
msgid ""
"reuse a previously created sandbox dir (SDIR) or, if it does not exist, "
"create it"
msgstr "นำ ไดเรกทอรี Sandbox (SDIR) ที่สร้างไว้ก่อนหน้านี้มาใช้ใหม่ หรือสร้างขึ้นมาถ้าเกิดไม่มีอยู่"

#: ../bin/apport-valgrind.py:60
msgid ""
"do  not  create  or reuse a sandbox directory for additional debug symbols "
"but rely only on installed debug symbols."
msgstr ""
"ไม่ต้องสร้างหรือนำไดเรกทอรี Sandbox มาใช้ใหม่สำหรับสัญลักษณ์การดีบั๊ก "
"แต่ให้อ้างอิงเฉพาะสัญลักษณ์การดีบั๊กที่ติดตั้งเท่านั้น"

#: ../bin/apport-valgrind.py:69
msgid ""
"reuse a previously created cache dir (CDIR) or, if it does not exist, create "
"it"
msgstr "ใช้ไดเรกทอรีแคช (CDIR) ที่สร้างไว้ก่อนหน้านี้มาใช้ใหม่ หรือสร้างขึ้นมาถ้าเกิดไม่มีอยู่"

#: ../bin/apport-valgrind.py:78
msgid "report download/install progress when installing packages into sandbox"
msgstr "รายงานความคืบหน้าของการดาวน์โหลด/ติดตั้งระหว่างติดตั้งแพกเกจไปที่ Sandbox"

#: ../bin/apport-valgrind.py:86
msgid ""
"the executable that is run under valgrind's memcheck tool for memory leak "
"detection"
msgstr ""

#: ../bin/apport-valgrind.py:129
#, python-format
msgid "Error: %s is not an executable. Stopping."
msgstr "ผิดพลาด: %s ไม่ใช่แฟ้มปฏิบัติการ กำลังหยุดทำงาน"

#: ../data/apportcheckresume.py:68
msgid ""
"This occurred during a previous suspend, and prevented the system from "
"resuming properly."
msgstr "นี่เกิดขึ้นระหว่างการพักเครื่องครั้งที่ผ่านมา และป้องกันไม่ให้ระบบทำงานต่อได้อย่างถูกต้อง"

#: ../data/apportcheckresume.py:73
msgid ""
"This occurred during a previous hibernation, and prevented the system from "
"resuming properly."
msgstr "นี่เกิดขึ้นระหว่างการไฮเบอร์เนตครั้งที่ผ่านมา และป้องกันไม่ให้ระบบทำงานต่อได้อย่างถูกต้อง"

#: ../data/apportcheckresume.py:81
msgid ""
"The resume processing hung very near the end and will have appeared to have "
"completed normally."
msgstr ""
"การดำเนินการที่กำลังจะดำเนินการต่อไปนั้นหยุดทำงานชั่วคราวเมื่อใกล้จะจบแล้ว "
"และจะเสร็จสมบูรณ์โดยปกติ"

#: ../data/kernel_oops.py:30
msgid "Your system might become unstable now and might need to be restarted."
msgstr "ระบบของคุณอาจไม่เสถียรแล้วในขณะนี้ และต้องเริ่มการทำงานของระบบใหม่"

#: ../gtk/apport-gtk.desktop.in.h:1 ../kde/apport-kde-mime.desktop.in.h:1
#: ../kde/apport-kde.desktop.in.h:1
msgid "Report a problem..."
msgstr "รายงานปัญหา"

#: ../gtk/apport-gtk.desktop.in.h:2 ../kde/apport-kde-mime.desktop.in.h:2
#: ../kde/apport-kde.desktop.in.h:2
msgid "Report a malfunction to the developers"
msgstr ""

#: ../gtk/apport-gtk.py:184
#, python-format
msgid "Sorry, the application %s has stopped unexpectedly."
msgstr "ขออภัย โปรแกรม %s หยุดทำงานอย่างกะทันหัน"

#: ../gtk/apport-gtk.py:187
#, python-format
msgid "Sorry, %s has closed unexpectedly."
msgstr "ขออภัย %s ปิดลงอย่างกะทันหัน"

#: ../gtk/apport-gtk.py:192 ../kde/apport-kde.py:210 ../kde/apport-kde.py:262
#, python-format
msgid "Sorry, %s has experienced an internal error."
msgstr "ขออภัย %s ประสบปัญหาภายใน"

#: ../gtk/apport-gtk.py:215 ../gtk/apport-gtk.ui.h:14 ../kde/apport-kde.py:203
msgid "Send"
msgstr "ส่ง"

#: ../gtk/apport-gtk.py:233 ../gtk/apport-gtk.py:665 ../gtk/apport-gtk.ui.h:11
#: ../kde/apport-kde.py:326
msgid "Show Details"
msgstr "แสดงรายละเอียด"

#: ../gtk/apport-gtk.py:246 ../kde/apport-kde.py:254 ../kde/apport-kde.py:272
msgid "Continue"
msgstr "ทำต่อไป"

#: ../gtk/apport-gtk.py:270
#, python-format
msgid "The application %s has stopped responding."
msgstr "โปรแกรม %s หยุดตอบสนองแล้ว"

#: ../gtk/apport-gtk.py:274
#, python-format
msgid "The program \"%s\" has stopped responding."
msgstr "โปรแกรม \"%s\" หยุดตอบสนองแล้ว"

#: ../gtk/apport-gtk.py:291 ../kde/apport-kde.py:218
#, python-format
msgid "Package: %s"
msgstr "แพกเกจ: %s"

#: ../gtk/apport-gtk.py:297 ../kde/apport-kde.py:225
msgid "Sorry, a problem occurred while installing software."
msgstr "ขออภัย เกิดปัญหาขณะติดตั้งซอฟต์แวร์"

#: ../gtk/apport-gtk.py:309 ../gtk/apport-gtk.py:333 ../kde/apport-kde.py:234
#, python-format
msgid "The application %s has experienced an internal error."
msgstr "โปรแกรม %s ประสบปัญหาภายใน"

#: ../gtk/apport-gtk.py:315 ../kde/apport-kde.py:241
#, python-format
msgid "The application %s has closed unexpectedly."
msgstr "โปรแกรม %s ปิดลงอย่างกะทันหัน"

#: ../gtk/apport-gtk.py:346 ../gtk/apport-gtk.ui.h:7 ../kde/apport-kde.py:267
msgid "If you notice further problems, try restarting the computer."
msgstr "ถ้าคุณประสบปัญหาเพิ่มเติม ให้ลองเริ่มการทำงานของคอมพิวเตอร์ใหม่อีกครั้ง"

#: ../gtk/apport-gtk.py:351 ../kde/apport-kde.py:274
msgid "Ignore future problems of this type"
msgstr "เพิกเฉยต่อปัญหาครั้งหน้าของประเภทนี้"

#: ../gtk/apport-gtk.py:669 ../kde/apport-kde.py:323
msgid "Hide Details"
msgstr "ซ่อนรายละเอียด"

#: ../gtk/apport-gtk.ui.h:1 ../kde/apport-kde.py:545 ../kde/apport-kde.py:588
msgid "Apport"
msgstr "Apport"

#: ../gtk/apport-gtk.ui.h:2
msgid "Cancel"
msgstr "ยกเลิก"

#: ../gtk/apport-gtk.ui.h:3
msgid "OK"
msgstr "ตกลง"

#: ../gtk/apport-gtk.ui.h:4
msgid "Crash report"
msgstr "รายงานความผิดพลาด"

#: ../gtk/apport-gtk.ui.h:5
msgid "<big><b>Sorry, an internal error happened.</b></big>"
msgstr "<big><b>ขออภัย เกิดข้อผิดพลาดภายใน</b></big>"

#: ../gtk/apport-gtk.ui.h:8
msgid "Remember this in future"
msgstr ""

#: ../gtk/apport-gtk.ui.h:9
msgid "Ignore future problems of this program version"
msgstr "เพิกเฉยต่อปัญหาในภายหลังที่เกิดขึ้นบนโปรแกรมรุ่นนี้"

#: ../gtk/apport-gtk.ui.h:10
msgid "Relaunch this application"
msgstr ""

#: ../gtk/apport-gtk.ui.h:12
msgid "_Examine locally"
msgstr "_ตรวจสอบในเครื่อง"

#: ../gtk/apport-gtk.ui.h:13
msgid "Don't send"
msgstr ""

#: ../gtk/apport-gtk.ui.h:15
msgid "<big><b>Collecting problem information</b></big>"
msgstr "<big><b>กำลังรวบรวมข้อมูลของปัญหา</b></big>"

#: ../gtk/apport-gtk.ui.h:16
msgid ""
"Information is being collected that may help the developers fix the problem "
"you report."
msgstr "กำลังรวบรวมข้อมูลซึ่งช่วยให้นักพัฒนาแก้ไขปัญหาที่คุณรายงานไป"

#: ../gtk/apport-gtk.ui.h:18
msgid "<big><b>Uploading problem information</b></big>"
msgstr "<big><b>กำลังอัพโหลดข้อมูลของปัญหา</b></big>"

#: ../gtk/apport-gtk.ui.h:19 ../kde/apport-kde.py:506
msgid ""
"The collected information is being sent to the bug tracking system. This "
"might take a few minutes."
msgstr "ข้อมูลที่รวบรวมมากำลังจะถูกส่งไปยังระบบติดตามบั๊ก การกระทำนี้จะใช้เวลาเพียงไม่กี่นาที"

#: ../kde/apport-kde-mimelnk.desktop.in.h:1
msgid "Apport crash file"
msgstr "แฟ้มความล้มเหลว Apport"

#: ../kde/apport-kde.py:257
msgid "Leave Closed"
msgstr "ปล่อยให้ปิดไป"

#: ../kde/apport-kde.py:258 ../kde/apport-kde.py:427
msgid "Relaunch"
msgstr "เรียกใหม่"

#: ../kde/apport-kde.py:351
msgid "Username:"
msgstr "ชื่อผู้ใช้:"

#: ../kde/apport-kde.py:352
msgid "Password:"
msgstr "รหัสผ่าน:"

#: ../kde/apport-kde.py:455
msgid "Collecting Problem Information"
msgstr ""

#: ../kde/apport-kde.py:458
msgid ""
"The collected information can be sent to the developers to improve the "
"application. This might take a few minutes."
msgstr ""
"ข้อมูลที่รวบรวมมาสามารถส่งไปให้นักพัฒนาเพื่อให้ปรับปรุงโปรแกรมได้ "
"การกระทำนี้จะใช้เวลาเพียงไม่กี่นาที"

#: ../kde/apport-kde.py:503
msgid "Uploading Problem Information"
msgstr ""
